services:
  # Backend API
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/app/databases/erp.db
      - PYTHONPATH=/app/backend
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    volumes:
      - ./databases:/app/databases
      - ./logs:/app/logs
    command: ["python", "backend/api.py"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Streamlit
  frontend:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app/backend
      - API_URL=http://backend:8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    volumes:
      - ./databases:/app/databases
    command: ["streamlit", "run", "frontend/streamlit_app.py", "--server.address", "0.0.0.0"]
    depends_on:
      - backend